<?php

/**
 * @file
 * Contains boi_search_path_alter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function boi_search_path_alter_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
            // Main module help for the boi_search_path_alter module.
        case 'help.page.boi_search_path_alter':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Module for altering Search result URL based on Bundle') . '</p>';
            return $output;

        default:
    }
}







/**
 * Implements hook_preprocess_search_result().
 */
function boi_search_path_alter_preprocess_search_result(&$variables) {
    $node = $variables['result']['node'];
    $type = $node->getType();
    kint($type);

    switch($type)
    {
        case 'second_sliders':
            if($node->get('field_slider_category')->getValue()[0]['value'] == 'e-services')
            {
                $eurl  = $node->get('field_e_services_url')->getValue()[0]['value'];
                if($eurl && strpos($eurl, '#') !== 0){
                    $variables['url'] = \Drupal\Core\Url::fromUserInput($eurl)->toString();
                }
            }
            
            break;
        case 'banner':

            $banner_link = $node->get('field_banner_link')->getValue()[0]['uri'];
            if($banner_link && strpos($banner_link, 'internal:#') !==0)
            {
                $variables['url'] = \Drupal\Core\Url::fromUri($banner_link)->toString();   
            }

            break;


        default:

    }
}